ALTER TABLE T_PAYMENT_METHOD ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 AFTER id;
ALTER TABLE T_IDENTIFICATION ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 AFTER id;
ALTER TABLE T_IDENTIFICATION_IMAGE ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 AFTER id;
ALTER TABLE T_KYC_CASE ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 AFTER id;

CREATE INDEX I_PAYMENT_METHOD_tenant ON T_PAYMENT_METHOD(tenant_id);
CREATE INDEX I_IDENTIFICATION_tenant ON T_IDENTIFICATION(tenant_id);
CREATE INDEX I_IDENTIFICATION_IMAGE_tenant ON T_IDENTIFICATION_IMAGE(tenant_id);
CREATE INDEX I_KYC_CASE_tenant ON T_KYC_CASE(tenant_id);
