spring:
    jackson:
        default-property-inclusion: non_null
        use-jackson2-defaults: true
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: false
            FAIL_ON_NULL_FOR_PRIMITIVES: false
            ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
        mapper:
            ACCEPT_CASE_INSENSITIVE_ENUMS: true
            ACCEPT_CASE_INSENSITIVE_PROPERTIES: true

    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB

server:
    port: 8081
    error:
        whitelabel:
            enabled: false
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain
        min-response-size: 512

management:
    endpoint:
        health:
            show-details: always
        info:
            git:
                mode: full
    endpoints:
        web:
            exposure:
                include: "beans,flyway,health,info,scheduledtasks,mappings"

logging:
    level:
        root: INFO
        com.amazonaws: ERROR
        org.springframework: INFO
        com.wutsi: DEBUG
        springfox: ERROR

    pattern:
        console: "%d Type=%level Logger=%c Thread=%thread %m%n"
        file: "%d Type=%level Logger=%c Thread=%thread %m%n"

ndopify:
    server:
        api:
            base-url: http://localhost:8080
