UPDATE T_AGENT SET mobile_change_id = NULL;
DELETE FROM T_IDENTITY_CHANGE;
DELETE FROM T_MOBILE_CHANGE;
DELETE FROM T_AGENT;

DELETE FROM T_AUTH_FACTOR;
DELETE FROM T_USER_APPLICATION_ROLE;
DELETE FROM T_USER_APPLICATION;
DELETE FROM T_USER;

DELETE FROM T_ROLE;
DELETE FROM T_LOCATION;
DELETE FROM T_TENANT;
