DELETE FROM T_AGENT_NEIGHBORHOOD;
DELETE FROM T_AGENT;

DELETE FROM T_IDENTIFICATION_IMAGE;
DELETE FROM T_IDENTIFICATION;
DELETE FROM T_PAYMENT_METHOD;
DELETE FROM T_PARTY;

DELETE FROM T_AUTH_FACTOR;
DELETE FROM T_USER_APPLICATION_ROLE;
DELETE FROM T_USER_APPLICATION;
DELETE FROM T_USER;

DELETE FROM T_ROLE;
DELETE FROM T_LOCATION;
DELETE FROM T_TENANT;
