name: ndopify-dto

on:
    push:
        branches:
            - main
        paths:
            - 'modules/ndopify-dto/**'
            - '.github/workflows/ndopify-dto-main.yml'
            - '!modules/ndopify-dto/*.md'

permissions:
    contents: write
    packages: write

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v7
            -   name: JDK
                uses: actions/setup-java@v5
                with:
                    distribution: 'zulu'
                    java-version: 17
            -   name: Set up Maven
                uses: stCarolas/setup-maven@v5.1
                with:
                    maven-version: 3.10.0
            -   name: Build
                env:
                    GITHUB_USER: ${{github.actor}}
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                run: |
                    mvn -s settings.xml --non-recursive install
                    cd modules/ndopify-dto
                    git config user.email "actions@github.com"
                    git config user.name "GitHub Actions"
                    git pull
                    mvn -q -B -X release:prepare release:perform
