name: ndopify-partner-central-pr

on:
    pull_request:
        paths:
            - 'modules/ndopify-partner-central/**'
            - '.github/workflows/ndopify-partner-central-main.yml'
            - '!modules/ndopify-partner-central/*.md'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v7
            -   name: JDK
                uses: actions/setup-java@v6
                with:
                    distribution: 'zulu'
                    java-version: 17

            -   name: Build
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                    KIMI_API_KEY: ${{secrets.KIMI_API_KEY}}
                    MTN_COLLECTION_SUBSCRIPTION_KEY: ${{secrets.MTN_COLLECTION_SUBSCRIPTION_KEY}}
                run: |
                    mvn -q -s settings.xml --non-recursive install
                    cd modules/ndopify-partner-central
                    mvn -Dspring.datasource.username=root -Dspring.datasource.password=root -q -s ../../settings.xml install

            -   name: Add coverage to PR
                id: jacoco
                uses: madrapps/jacoco-report@v1.8.0
                with:
                    paths: |
                        ${{ github.workspace }}/modules/ndopify-partner-central/target/site/jacoco/jacoco.xml
                    token: ${{ secrets.GITHUB_TOKEN }}
                    min-coverage-overall: 90
                    min-coverage-changed-files: 90

            -   name: Upload JaCoCo Report
                uses: actions/upload-artifact@v7
                with:
                    name: jacoco-report
                    path: modules/ndopify-partner-central/target/site/jacoco/**/*
