name: ndopify-server


on:
    push:
        branches:
            - main
        paths:
            - 'modules/ndopify-server/**'
            - '.github/workflows/ndopify-server-main.yml'
            - '!modules/ndopify-server/*.md'

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:9.7
                env:
                    MYSQL_USER: admin
                    MYSQL_PASSWORD: admin
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: ndopify
                ports:
                    - 3306:3306

        steps:
            -   uses: actions/checkout@v7
            -   name: JDK
                uses: actions/setup-java@v5
                with:
                    distribution: 'zulu'
                    java-version: 17

            -   name: Build
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                    KIMI_API_KEY: ${{secrets.KIMI_API_KEY}}
                    MTN_COLLECTION_SUBSCRIPTION_KEY: ${{secrets.MTN_COLLECTION_SUBSCRIPTION_KEY}}
                run: |
                    mvn -q -s settings.xml --non-recursive install
                    cd modules/ndopify-server
                    mvn -Dspring.datasource.username=root -Dspring.datasource.password=root -q -s ../../settings.xml install

            -   name: Upload app bundle
                uses: actions/upload-artifact@v6
                with:
                    name: appbundle
                    path: modules/ndopify-server/target/*.jar

            -   name: Upload JaCoCo Report
                uses: actions/upload-artifact@v6
                with:
                    name: jacoco
                    path: modules/ndopify-server/target/site/jacoco/**/*

            -   name: Generate JaCoCo Badge
                uses: cicirello/jacoco-badge-generator@v2
                with:
                    generate-branches-badge: false
                    jacoco-csv-file: modules/ndopify-server/target/site/jacoco/jacoco.csv
                    coverage-badge-filename: ndopify-server-jacoco.svg

            -   name: Commit the badge (if it changed)
                continue-on-error: true
                run: |
                    if [[ `git status --porcelain` ]]; then
                      git config user.email "actions@github.com"
                      git config user.name "GitHub Actions"
                      git add -A
                      git commit -m "Autogenerated JaCoCo coverage badge"
                      git push
                    fi
